apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: basic-ingress
  namespace: default
    # annotations:
    # kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: wordpress
  rules:
    - host: host.minikube.internal
      http:
        paths:
          # - host: localhost
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
