apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/valeriya-k8s-repo:valeriya-k8s-wordpress
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env: 
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mariadb-configmap
                  key: database_url
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress
            # secretKeyRef:
              # name: mariadb-secret
                #  key: mariadb-root-password
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_NAME
              value: wordpress
      imagePullSecrets:
         - name: regcred
